source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-partial'
gem 'unicorn'
gem 'jammit'
gem 'github_api'
gem 'sass'
gem 'compass'
gem 'stipe'
gem 'redis'
gem 'html-pipeline'
gem 'gemoji'
gem 'toadstool'