source 'http://rubygems.org'
ruby '1.9.3'

gem 'sinatra'
gem 'sinatra-partial'
gem 'unicorn'
gem 'jammit'
gem 'closure-compiler'
gem 'github_api'
gem 'sass'
gem 'compass'
gem 'stipe'
gem 'redis'
gem 'html-pipeline'
gem 'gemoji'
gem 'newrelic_rpm'
gem 'sinatra-respond_to'
gem 'RedCloth'
gem 'haml'

# gem 'toadstool'

gem 'chairman'