require "./vendor/jquery-1.8.2"
require "./vendor/Prettify/prettify"

require "./vendor/Prettify/lang-apollo"
require "./vendor/Prettify/lang-basic"
require "./vendor/Prettify/lang-clj"
require "./vendor/Prettify/lang-css"
require "./vendor/Prettify/lang-dart"
require "./vendor/Prettify/lang-erlang"
require "./vendor/Prettify/lang-go"
require "./vendor/Prettify/lang-hs"
require "./vendor/Prettify/lang-lisp"
require "./vendor/Prettify/lang-llvm"
require "./vendor/Prettify/lang-lua"
require "./vendor/Prettify/lang-matlab"
require "./vendor/Prettify/lang-ml"
require "./vendor/Prettify/lang-mumps"
require "./vendor/Prettify/lang-n"
require "./vendor/Prettify/lang-pascal"
require "./vendor/Prettify/lang-proto"
require "./vendor/Prettify/lang-r"
require "./vendor/Prettify/lang-rd"
require "./vendor/Prettify/lang-scala"
require "./vendor/Prettify/lang-scss"
require "./vendor/Prettify/lang-sql"
require "./vendor/Prettify/lang-tcl"
require "./vendor/Prettify/lang-tex"
require "./vendor/Prettify/lang-vb"
require "./vendor/Prettify/lang-vhdl"
require "./vendor/Prettify/lang-vim"
require "./vendor/Prettify/lang-wiki"
require "./vendor/Prettify/lang-xq"
require "./vendor/Prettify/lang-yaml"

require "./vendor/Prettify/prettify-loader"
require "./main"
require "./comments"

